# Generated by Django 4.2.10 on 2024-02-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
