# Generated by Django 4.2.10 on 2024-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_email_token_userprofile_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temporary_email',
            field=models.EmailField(blank=True, max_length=48),
        ),
    ]
